# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99a6aaf2c2068224bb7b2c8ed16afda5fea52299f3ae5dffe34e8b5cb38fe3c9d224b2a49c2e90917dc20b0ba4ec25cedd9e1449e12621204dabf72bf5aef6a

test:
  secret_key_base: 038c1a6f0d14544922fcade2990b4ea65d08353bf0a0c15c8fe967fffdbd8b87b309874b30702db17b5bc39449e6669cafeeab4ecc1c4cfd1039fa6100002e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
